### ISSUE TITLE
Need some help. 

### ISSUE THREAD

**Issue by CryptoKey98** [genboy/Festival#131]
Hello. Having some trouble with your plugin and was wondering if you can help me find a solution.

Okay so, I want to make it so VIP rank (permission) can only fly on my server. But if I set flight to true in config, VIPs can't fly even though they have /fly command. I was wondering if there's a way to work around this. I mainly use your plugin because I want to disable PvP in certain areas on a map. 

Is there a way to allow flying to VIP permission group instead of white-listing players?

**Comment by genboy** [comment]
Hi @CryptoKey98 
Flight is also available when player has permisssion 'festival' and/or 'festival.access'. 
If you can include those permissions in your VIP ranks then the VIPs will be able to fly.
Hope you can manage that (maybe need pureperms).

**Comment by CryptoKey98** [comment]
But will that also give them the access to PvP in restricted areas or no?

**Comment by CryptoKey98** [comment]
@genboy I also wanted to setup no fly zones even for VIP ranks.

**Comment by genboy** [comment]
@CryptoKey98 you are correct about that (loosing pvp restriction too), i have not yet made sub permissions for all flag types to do that, I'll see if i can do that. ( like festival.flag.fly and festival.flag.pvp ) 
While your goal sounds very basic, i think it is beyond Festival 's scope right now. 
Just an idea; maybe you can try to combine the area event command options with the area perms flag true in combination with another fly plugin and/or your VIP rank extension. Then you can distinguish the VIP players because the commands on area enter and leave will only execute if the player has the VIP permissions.
