### ISSUE TITLE
Hellp

### ISSUE THREAD

**Issue by Ahoy2533** [genboy/Festival#174]
Why i can't build in edit area??

**Comment by genboy** [comment]
Hi @Ahoy2533, i'm not sure 
In game experience can be a bit confusing because of many things, ie. OP permissions, gamemodes, Festival whitelisting, Multiple Festival flags and other plugin settings. 

About Festival Flags: 
Any flag true will protect the area and the players in it. 
edit: true (on) means no breaking/building by players. 
shoot: true (on) means no shooting by players.

Please also see [https://github.com/genboy/Festival/wiki](https://github.com/genboy/Festival/wiki)
Hope you can enjoy Festival

**Comment by Ahoy2533** [comment]
Ow, i know now, that's because multiworld plugin i think.. but now, why i can't pvp in pvp=off area? Im not using multiworld

**Comment by genboy** [comment]
Hi @Ahoy2533, did you check god flag is off?
Sorry but sometimes I also forget other flag combinations so we should check everything..
I recently tested non-PVP area inside a PVP area (helping @Snickerzzz testing) and it worked well. 
Let me know if it's still not working, thank you

**Comment by Ahoy2533** [comment]
Still not working, watch dis
https://tinyurl.com/y4rzdz54

**Comment by genboy** [comment]
Hi @Ahoy2533 , thank you for the video report. 
what i see could be a problem;
- the player cinnamonsoda48 is whitelisted in that area < i think this is it .. can't get hurt
- iprotector area flags / level defaults?

Might want to make sure server defaults are PVP allowed, then level defaults are PVP and then large Festival area (without iprotector!) set No-PVP and last smaller area inside set to PVP.

**Comment by genboy** [comment]
Hi @Ahoy2533 , is this problem solved?

**Comment by Ahoy2533** [comment]
Idk, I haven't played minecraft 2 weeks ago, but I think it's already good.
