### ISSUE TITLE
My members cant do anything with their surv world

### ISSUE THREAD

**Issue by dapwestwood** [genboy/Festival#224]
I dont get any fe plugins change on their survival world, then why they cant break or build anything when i use this plugins?, Is it make the Another world to be festival?

**Comment by genboy** [comment]
Hi @dapwestwood, in version 2.0.0 level flags can protect levels, set in the level management menu. More people are having issues with the flag protections for levels, i will adjust this in future plugin versions,  
For now, please try ingame the Festival menu >the level management menu > each level the first option is to turn on/off the flag functions for that level. (see [issues](https://github.com/genboy/Festival/issues/222#issuecomment-518036844) ) , hope that helps to solve your problem, otherwise let me know.

**Comment by dapwestwood** [comment]
I turn on and off the level flag, and still not worked

**Comment by genboy** [comment]
Ok, there are many things we should check to solve this. 
- Could you inform me on pmmp version, Festival version and other active plugins? 
- Festival 2.0.x should create level.json, areas.json and config.json. Can you check those files are in the plugins/Festival folder? 
- Maybe if there is a config.yml - save it as a backup and remove it or change it's name (to be sure config.json is used)
- Or if there is a old config.yml used for update to version 2.0.0 you can add a new option
"LevelControl": off - Like [here](https://github.com/genboy/Festival/blob/master/resources/config.yml) - then remove config.json and level.json and restart
- or can look/adjust in the plugins/Festival/level.json file data see if levelcontrol variable is on or off for the target level.

Above info might bring up a solution, otherwise let me know

**Comment by dapwestwood** [comment]
1. I using festivaldev100, i using worldprotect,economyland
2.yes there are level.json,config.yml,areas. And etc.
3.level control is set to false

**Comment by genboy** [comment]
Hi @dapwestwood, thank for the info. I think worldprotect is also protecting your world, right? 
could you pleae check that first? 
Then I suppose Festival is only handy for creating area's, could you try setup and area with priority 1 and edit flag off? In that case players should be able to build in that area.

**Comment by dapwestwood** [comment]
Yeah sure, but it was survival world and i wont do that

**Comment by dapwestwood** [comment]
Yea i set it off level flag on survival world

**Comment by genboy** [comment]
Ok, do i understand correctly you can use Festival now in combination with worldprotect?

**Comment by dapwestwood** [comment]
Yes i do not protecting the world

**Comment by genboy** [comment]
Hi, so you do not protect the world with the Worldprotect plugin now and you use the Festival level flags? Is that working ok? Just curious

**Comment by dapwestwood** [comment]
Yea i do not protect the world, and i turned off the level flag. Then its not worked

**Comment by genboy** [comment]
Ah, ok. Is your issue solved then?

**Comment by dapwestwood** [comment]
No :(

**Comment by genboy** [comment]
Humm, can you see if there is code in the levels.json? If you want do not want to use the level flags the variable 'levelcontrol' should be 'off' for that specific level. Or 'on' if you want to use them.  I've spotted a bug that sometimes the levelcontrol variable is false, instead of 'off'.

For the flags, just to check; edit flag 'on' (toggle right) means no edit.

**Comment by dapwestwood** [comment]
Yea there.is a level.json file. And the levelcontrol variable are set to off. And the flag are set to on by its default

**Comment by genboy** [comment]
If the levelcontrol is set to 'off' the flags should not have an effect on that level, then it is not Festival protecting the level. But if there's an error in Festival maybe we should check;
Could you check that when the level edit flag is set to off, players are still not allowed to edit? 
Thank you

**Comment by dapwestwood** [comment]
Yea that work when i set 'edit' to the left

**Comment by genboy** [comment]
Ok, good to know. Is this issue solved then?
There is a new [dev-update](https://poggit.pmmp.io/ci/genboy/Festival/Festival) ready if you like

**Comment by dapwestwood** [comment]
Okay will try it soon
