### ISSUE TITLE
floating area tags?

### ISSUE THREAD

**Issue by itzfrozt** [genboy/Festival#240]
is there a way to get rid of the floating area tags? 
![image](https://user-images.githubusercontent.com/52588179/64083298-af2f3c00-cceb-11e9-9ab7-5c6fc8ca8e14.png)

**Comment by genboy** [comment]
Hi @itzfrozt, good you noticed this, i'll have to check and fix this because the 2 ways to do that are not workin now.

1. Set area floating titles display in configs
 ![config](https://camo.githubusercontent.com/91c4672d25835e3c4ab0ab1eb1e8b8c172d01c6e/68747470733a2f2f67656e626f792e6e65742f77702d636f6e74656e742f75706c6f6164732f323031392f30362f6d616e616765725f636f6e66696775726174696f6e2e706e67)

2. Set msg flag on area

The fix is in progress

**Comment by genboy** [comment]
@itzfrozt I found some problems that mix up the ops/regular area title display, it will take some time befor i can fix that.
For now can you see if it will do to toggle the floating titles with cmd: /fe titles

**Comment by itzfrozt** [comment]
that worked perfectly! thank you, i don't care for the area titles anyway, would rather not have them at all tbh, take as much time as you need!
