### ISSUE TITLE
Can't Disable Area Message?

### ISSUE THREAD

**Issue by al5ina5** [genboy/Festival#279]
Hi there,

Thanks for a great plugin.

It seems that setting the message to 'off' in the configuration menu does not actually disable the messages.

Is this an intended feature or a bug?

Thanks.

**Comment by genboy** [comment]
Hi @al5ina5, nice to hear you like using Festival!
It's not only the flag that is used. The msg flag might work differently due to the configuration setting 'Area messages visible' - on/op/off. 
![afbeelding](https://user-images.githubusercontent.com/30810841/76689866-93153b80-663a-11ea-97be-a4920699067c.png)

(maybe you are op and still see the messages) You can play with this setting in combination with the msg flag. Hope it works for you, otherwise let me know. Cheers!

**Comment by al5ina5** [comment]
Thanks for the helpful reply! I haven actually been able to disable them since. I really appreciate it.

Do you have a Discord or something similar? I joined a Genboy Discord server but I don’t think you use it. Is there another one?

Thanks!

**Comment by genboy** [comment]
Hi, i have discord but i'm not that much online for chatting. I'll try if i can plan an hour a week for Festival support chat. My server is https://discordapp.com/invite/JFYeqYn
