### ISSUE TITLE
TnT flag isn't working

### ISSUE THREAD

**Issue by creeperplayer20** [genboy/Festival#305]
Hello, I have a big problems with TnT and Explostion flags. No matter if they're on or off. They're still not working even without op.
![area_flags](https://user-images.githubusercontent.com/42560781/119669155-1bdf5800-be38-11eb-9283-81b6fea58459.png)
![no_op_before_ignition](https://user-images.githubusercontent.com/42560781/119669184-24379300-be38-11eb-8b95-e38fd43df2c7.png)
![booom](https://user-images.githubusercontent.com/42560781/119669202-28fc4700-be38-11eb-986e-4e961a1d8cbb.png)

**Comment by genboy** [comment]
Ouch! Thank you @creeperplayer20 for reporting this, i will check and fix this hopely in the next couple of days.

**Comment by genboy** [comment]
Hi @creeperplayer20, I'm not sure what Festival version you use but you should use [version Festival_dev_122](https://poggit.pmmp.io/r/120410/Festival_dev-122.phar) because older versions will cause problems with newer PMMP versions due to several coding updates. I hope to [R]elease a new version soon, sorry if it is was clear which version you should use.
I've tested the TNT flag with [Festival dev #122](https://poggit.pmmp.io/r/120410/Festival_dev-122.phar), no problems there. 

https://user-images.githubusercontent.com/30810841/120014346-3ce3ac80-bfe2-11eb-9cba-86c40b738844.mp4


So I'm wondering, maybe you have another area overlay? Hope to find out what is causing your TNT problem.

Thank you for your time, it helps me improving Festival and skills up my amateur marketing :)  
Cheers

**Comment by genboy** [comment]
Hi @creeperplayer20, closed with redirection to the new version. Please try the latest [v2.1.3](https://github.com/genboy/Festival/releases/tag/2.1.3) - [direct phar phar](https://github.com/genboy/Festival/releases/download/2.1.3/Festival.phar)
