### ISSUE TITLE
Problems with “fly” in unprotected areas 

### ISSUE THREAD

**Issue by kevinishawesome** [genboy/Festival#89]
Not sure if you saw my response on another issue, so I thought it would be best to open a new issue.. anyway 

[unprotected area] I’m having seriously problem regarding the fly functionality.. if I disable fly, it disables it for everyone, and not even my staff who have op can fly.. but if I enable fly, everyone who visits the server starts flying..

I’ve tried installing BlazinFly, but it’s useless.. basically your plugin disables flight everywhere except the areas that I make..
 (protected areas) I can just add my staff to whitelist and flight works fine for them there in creative

So what happens when I put fly: false to all 3 configs..

Is that when anyone enters the server (unprotected areas) a message pops up saying “Flying Allowed here”

Now when I use other plugin /fly to disable fly.. it successfully disables fly but.. your plugin right away pops a message “flying is allowed here” and all of a sudden I start flying again
(This is when I joined my server through IP to test, with default perms) 

(Now as server owner)
So as the server owner, when I join the server I get the message “Flying allowed here”, regardless if flying is enabled or disabled.. 

So most probably there’s a whitelist for owners I’m assuming.. maybe you could enable that whitelist for unprotected areas for all of us to add other staff names to it as well... because trust me.. I’ve tried 2 plugins PCFly and BlazinFly.. and nothing works with your plugin :/

**Comment by genboy** [comment]
Hi @kevinishawesome, thank you for describing the complete issue you have. 
Maybe I can help a bit by explaining there is no whitelist for owners or anything, ops and area whitelisted players should not be bound by the area flags. 
I'll first check/reproduce the flight settings you mention to see the problem and try fix it. Will keep you posted.

**Comment by kevinishawesome** [comment]
That’s great, Thank you for a quick response. Hoping you will be able to reproduce the issue, if not I’ll make a video of it.. maybe that will help

**Comment by genboy** [comment]
@kevinishawesome i've checked some basic Festival config functions on flight, we'll have to check configurations first, then we can look what's happening in the server and with other plugins. 

I hope you can check festival and server configs with the info below. (and maybe temporary filter out interfering 3dparty settings). I will check this also in the latest dev versions i've made.

> Assuming you use Festival version 1.0.7 (or 1.0.6-x  flight flag code unchanged)
--- 
In config.yml the first Default flag config list is used for levels(worlds), unless there is a specified world flag-list added in the config.yml. 
Without other world managing plugins interfering(!) the default flag config proces should work like this;

**Default flags** = server (any level) unprotected area defaults
_If pmmp server properties flight is on, and Default Flight flag is TRUE, only players should not be able to fly._

**Worlds->DEFAULT flags** = server default level unprotected area flag settings
_If player is in the server default level and Worlds->DEFAULT Flight flag is TRUE, only players should not be able to fly, if FALSE they can fly!_

**Worlds->(yourlevelname)** = server level 'yourlevelname' unprotected area flag settings
_If player is in the server default level and worlds->(yourlevelname) Flight flag is TRUE, only players should not be able to fly, if FALSE they can fly!_

--- 
The message 'Flying allowed here' is visible
- when enter an area, if you are not flying
- is always visible for ops if config Msgdisplay = op


> Does your player spawn directly in an area? And is this area in the default server level?
Then first check server properties (flight on), then the spawn area (! spawn protects players in many ways and overwrites most Festival functions), and then the Festival config default flags (flight true: no flying for players).

Take care of all the configs, if not solved please let me know

**Comment by kevinishawesome** [comment]
Ok so a follow up.

P.S all tests done on Admin Config (as Op, but not as owner) 

I have removed all the third party plugins and my spawn protection is disabled, because let’s face it, festival is already doing it everywhere..

More to note: The spawn area comes under unprotected area, flight works fine for all ops in protected areas, because I have them listed under the whitelist of each area. Otherwise the same problem there.. if it’s true it won’t allow flight no matter what the case, if false it allows everyone to fly. 

Now to answer your questions, my server does allow Flight, and I am using v1.0.7.

So for my server I believe the Default flags matter, but either way I change config on all 3 of them.

Now what I did is, I set the flight flag to “True” 

Removed all third party plugins that gave the function to /fly 

But still my staff can’t fly under unprotected areas, I think the only solution to this now is if you add a “whitelist” for unprotected areas (Default Config1) 

And maybe add another whitelist for Config2, so when ever a new area is created it automatically whitelist the mentioned players as it whitelist the creator, this will save the hassle of adding their name again and again to new areas.

**Comment by genboy** [comment]
Hi, thank you for checking everything again. I really regret it if the flight flag does not work as it should and want to get to the bottom of this. (Sorry if it is to much text)

--- 

I'm testing with pmmp 3.2.2,  server properties allow-flight=on, only festival 1.0.7 plugin installed & enabled, in Festival configs all Flight-flags are true, spawn in default world; a new normal world (unprotected area):

1. As an Op I can fly, as regular player I can not fly anywhere.
While ingame as regular player I opped myself from console and then I see the message 'Flying allowed here' (without any area! my fault in previous text, sorry) which is actually correct because I'm an Op again and see messages and flight is working. So far ok.

2. Then I created an area and set flight flag off (was true by default). 
As Op and as regular player I could fly inside the area. Flying outside the area (in to unprotected area) as regular player I dropped down with the message 'No flying here', as an Op i continued flying on without message or problems. That was as expected too.

3. Then I removed my playername from the area whitelist and set the Flight-flag true.
Now I deopped myself and as a regular player I couldn't fly anywhere, in or outside the area (unprotected area). As an Op i continued flying everywhere without problems. Pretty ok.

Steps 1 to 3 are a basic test for any flag. I think if you can not confirm this working with Pocketmine 3.0.0 - 3.2.3 we have to exchange more info on the server configs.

---

Something else I noticed, I have not learned yet about other owners/staff permissions groups to use in Pocketmine. Untill now Festival only knows to handle ops, area whitelisted players and players.
Can you explain how I should add players to a staffmemberlist on my pocketmine server for testing?
Thank you!

**Comment by kevinishawesome** [comment]
Hmm so according to you, when you assign op to someone he is automatically whitelisted in the unprotected areas?

Let me check in with InnovativeDevelopers and see what PMMP version they are using in their Pocketmine app for iOS

**Comment by kevinishawesome** [comment]
Ok so I talked to him, he’s using PMMP 3.3

**Comment by genboy** [comment]
Hi, i'll have to check up with version 3.3 (.0 ?), it's new and there might be some important issues to know about. 

What you mention about ops not flying is important.
As i understand now your server does not allow ops to fly by default. These are permissions set in the server, they may be managed with a permissions plugin (like purePerms). 
**If players and ops can not fly without Festival installed/enabled, Festival will not be able to change these fly restrictions.** 
Why? Because Festival is made to work instandly ingame for area event commands and protection, not player permission management on server level. That would interfere with other plugins and make Festival management very complicated at the moment. 
Festival only sets permissions for Festival command acces. (in the plugin.yml file, which is only available when you install the Festival .zip package, together with the devtools plugin)

So if your server allows flight for (certain) ops (owners?), then festival will respect that op-permission and not block the ops flight in area's with flight-flag true (flight blocked for players).

I hope you can find a way to manage the op/player server permissions.

**Comment by kevinishawesome** [comment]
Ok, I get what you’re saying.. but in pureperms nothing is disabled related to flight and in PM config settings, flight is allowed.. when I remove your plugin.. everything works fine.. everyone can fly in creative mode, including non ops.. as they should.. but with festival. If flight is allowed, everyone can fly in survival! That’s crazy!.. if disabled no one can fly not even ops

**Comment by genboy** [comment]
Ouch, that is not ok, sorry for the trouble. I will review the permission handling methods in Festival on this and if needed make an effort to embed playermodes handling.

**Comment by genboy** [comment]
Hi @kevinishawesome , i've checked and removed a regular isOp() check, in this 
dev version below the Flight function only depends on player permisssion 'festival' and player permission 'festival.access'. 
If you can grand one of these permissions to ops, Festival should allow them to fly in area's where flight flag is on (where other players are not allowed to fly).

Festival makes no difference between gamemodes yet. I'll see what it takes to implement the gamemodes into Festival, it would be a nice addition. 
Ops should fly anywhere first. Let me know what you can do with this.

[Festival_v1.0.7.9-dev.phar.zip](https://github.com/genboy/Festival/files/2453986/Festival_v1.0.7.9-dev.phar.zip)  (unzip in plugins folder - note here default configs flight are false - some new stuff might call for config action but should not bother)

**Comment by kevinishawesome** [comment]
Hmm thank you.. let me get the InDev to get it installed for my device through a core update, because he has some restrictions towards manual plugin installation, some security concerns. This could take a few days considering he’s a busy guy. I will keep you posted here! Thanks for checking in!

**Comment by genboy** [comment]
Ah, ok! Meanwhile I'll try to find out what's best to do with gamemode settings in Festival.

**Comment by kevinishawesome** [comment]
Hey genboy, sorry it took so long, but it worked! I gave my ops the “festival.access” permission and they were able to fly everywhere just like me!

**Comment by genboy** [comment]
Good to know! Enjoy!
Thank you for your feedback and patience.
The code changes will stay in development untill next release.

**Comment by salllaf** [comment]
Thank you for helping genboy fix this kevin. This was beating us down on our server as well :)) I've downloaded the dev to fix. Thanks genboy for the cool plugin!

**Comment by genboy** [comment]
@salllaf Thanks for sharing! All bug reports are welcome, I'm happy helping out making Festival work for you.

**Comment by Bruth78** [comment]
@genboy
Hey, I found this issue and I’m experiencing a similar one.
So basically everyone with gmc can’t fly. (without op) 
At first every Guest was able to fly so I turned flight in every Area to NoFly.
But how do i let ppl without op and with gmc fly?

**Comment by genboy** [comment]
Hi @Bruth78 , @salllaf , @kevinishawesome hope not to disturb you with this little announcement - next Festival update will have the Flightcontrol option, now testing [dev version](https://poggit.pmmp.io/ci/genboy/Festival/Festival/dev:82) Cheers!

**Comment by SchdowNVIDIA** [comment]
Nice. Thanks for fixing that.
