### ISSUE TITLE
Some flag ideas you could add

### ISSUE THREAD

**Issue by iZeaoGamer** [genboy/Festival#90]
So I was looking through the new updates you've added, and they're just brilliant. Infact, one of the best protection plugins I've seen for MCPE.
But the suggestions I would like to add, is maybe add a explosions flag. Why you may ask?
Well, you could add an explosions flag to this plugin so creepers or anything explosions related (Not TNT included), such as: Weather AKA Lightening, Creepers (With support of PureEntities or any AI plugins out there), and basically anything that has: Explosions related. (But again, not TNT included).
Also another suggestion I'd like to add is: Fire prevention, this follows up to the Lightening weather as well. This does not include flint and steel BTW. Or maybe what you could do, is just name the flag its self "Fire", which includes: Flint and steel, and anything fire related, and maybe add explosions flag as well, and move TNT flag to explosions, and add Weather / Lightening and creepers to the explosions flag.
That way, it's more easier to understand the flag's categories instead of just one thing.
Also one more thing that could potentially be a good idea to implement / add
A new flag called "weather". What is it you may ask?
You could control the weather system, and control: What weather it is in that area or world. What weather is, will and could always stay as that weather, so for example: If you protect a area, and you can do: /fe flag spawn weather rain, that would always put the weather to rain. And so on. This could potentially be a good idea, but not sure if that's a possible task to do.
Let me know your opinions on this. Thank you.

**Comment by genboy** [comment]
@iZeaoGamer Lightening, explosion, fire. Yes ofcourse! All are separated from TNT.
Thank you very much for your appreciation, your suggestions and creative ideas. 
Some are really thoughtfull and definitely worth to take on in Festival development. 

I found with Festival mindblowing ideas are possible using the area event command function alone. That's why I made it in the first place. 
Besides the core future, which still can be extended to many more events, all other development has gone into flags and area protection following the community feedback and input. 
Now Festival is also being used as a manager for not only area's but levels too. That's really cool!

I must admit the current configuration method for level protection is a bit complicated and I like people taking the trouble to be able to enjoy the full Festival experience, and especialy appreciate those who attribute good suggestions, thank you!
 
Weather! I'll have to check if local weather control is possible, in real life it definitely is now 0_~

**Comment by iZeaoGamer** [comment]
Well, thank you for taking my ideas into consideration. Means a lot.

**Comment by genboy** [comment]
@iZeaoGamer a small update because i do really like lighting and weather control for Festival Area's but..
allthough the latest 1.8 version contains the separated fire flag; to prevent the fire spreading i came up with a hacky function [(detecting all blockchanges and replacing fire blocks 1 y positon above with air)](https://github.com/genboy/Festival/blob/fd72552d1d342faa2210d68799fc59d3ef36d20b/src/genboy/Festival/Main.php#L1471)  which also renders the OP functionality on Fire flag useless. - i don't like the way i had to code it and should not go on using that code in combination with lightning etc..

I hope to create a better solution for the Fire flag and other block update/damage events with correct OP functionality in the future in Festival 2.

Latest weeks I made a lot of progress on Festival 2 and decided not to extend Festival 1.8 functionalities  further more. Important bug fixes will still be done untill Festival 2 is ready: including FormUI for easy control, another code structure and some of the flags will be completely rewritten. I probably dump the translations untill there is request for it. Just to let you know ..
